# Generated by Django 5.0.2 on 2024-05-03 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_extraservice_remove_camerateam_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camerateam',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extraservice',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
