# Generated by Django 5.0.2 on 2024-05-07 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_camerateam_prix'),
    ]

    operations = [
        migrations.AddField(
            model_name='camerateam',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='camera_team'),
        ),
    ]
