# Generated by Django 5.0.2 on 2024-05-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_camerateam_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraservice',
            name='reduction',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
