# Generated by Django 5.0.2 on 2024-05-07 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_extraservice_reduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salle',
            name='facebook',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='salle',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='salles/'),
        ),
        migrations.AlterField(
            model_name='salle',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='salles/'),
        ),
        migrations.AlterField(
            model_name='salle',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='salles/'),
        ),
        migrations.AlterField(
            model_name='salle',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='salles/'),
        ),
    ]
